theme: jekyll-theme-dinky
title: total-variation-sum-of-squares
description: Sum-of-squares hierarchies to solve the Total Variation norm minimization
show_downloads: true
google_analytics: UA-3278327-4
github:
  is_user_page: true
  is_project_page: true
  owner_url: https://ydecastro.github.io/
